#!/usr/bin/env python3
"""Emit static/css/_tokens.css from tokens/e3.tokens.json.

The first emitter of the new design system. The token file is platform-neutral
so later emitters (PowerPoint theme, print swatches) read the same source; this
one produces CSS custom properties.

Deliberately emits ONLY what the token file models. The old system has 123
tokens including category, status, rainbow-primitive and illustration-utility
families that the new file does not cover yet, so those stay declared in
general.css until they are modelled here. Emitting a partial :root that
shadowed them would break the site.

Run via `make tokens-new`.
"""
import json
import sys
from pathlib import Path

SRC = Path("tokens/e3.tokens.json")
OUT = Path("static/css/_tokens.css")

# Tier → media query. `laptop` is the base declaration in :root, so it has no
# query; the others override it. Order matters — later wins at equal specificity.
TIERS = [
    ("tablet", "@media (max-width: 64rem)"),
    ("phone",  "@media (max-width: 37.5rem)"),
    ("wide",   "@media (min-width: 90rem)"),
]
BASE_TIER = "laptop"


def flat_colors(node, prefix, out):
    """color.field.energy.text → --field-energy-text"""
    for k, v in node.items():
        if k.startswith("$"):
            continue
        if isinstance(v, dict) and "$value" in v:
            out[f"{prefix}-{k}" if prefix else k] = v["$value"]
        elif isinstance(v, dict):
            flat_colors(v, f"{prefix}-{k}" if prefix else k, out)


def main():
    if not SRC.exists():
        print(f"missing {SRC}", file=sys.stderr)
        return 1
    t = json.loads(SRC.read_text())

    lines = [
        "/* AUTO-GENERATED by build_tokens.py from tokens/e3.tokens.json.",
        "   Do not edit. Run `make tokens-new` after changing the token file.",
        "",
        "   Loaded before general.css so these resolve first. Only the families the",
        "   token file models are emitted; category, status, rainbow-primitive and",
        "   illustration-utility tokens remain in general.css until modelled here. */",
        "",
        ":root {",
    ]

    # ── colour ───────────────────────────────────────────────────────────────
    colors = {}
    flat_colors(t["color"], "", colors)
    lines.append("    /* colour — every value traces to the logo; see mark.* in the source */")
    for name, val in colors.items():
        lines.append(f"    --{name}: {val};")

    # ── type ─────────────────────────────────────────────────────────────────
    lines.append("")
    lines.append("    /* type */")
    for key, node in t["font"].items():
        if key.startswith("$"):
            continue
        if key == "weight":
            for w, wn in node.items():
                if not w.startswith("$"):
                    lines.append(f"    --fw-{w}: {wn['$value']};")
        else:
            fams = ", ".join(f"'{f}'" if " " in f else f for f in node["$value"])
            lines.append(f"    --font-{key}: {fams};")

    for role, node in t["scale"].items():
        if not role.startswith("$"):
            lines.append(f"    --fs-{role}: {node['$value'][BASE_TIER]};")
    for role, node in t["leading"].items():
        if not role.startswith("$"):
            lines.append(f"    --lh-{role}: {node['$value']};")
    for role, node in t["tracking"].items():
        if not role.startswith("$"):
            lines.append(f"    --tracking-{role}: {node['$value']};")

    # ── measure / space / radius / motion ────────────────────────────────────
    for group, prefix in (("measure", "measure"), ("space", "space"), ("radius", "radius")):
        lines.append("")
        lines.append(f"    /* {group} */")
        for k, node in t[group].items():
            if not k.startswith("$"):
                lines.append(f"    --{prefix}-{k}: {node['$value']};")

    lines.append("")
    lines.append("    /* motion — all of it behind prefers-reduced-motion */")
    for k, node in t["motion"].items():
        if k.startswith("$"):
            continue
        v = node["$value"]
        if isinstance(v, list):
            v = f"cubic-bezier({', '.join(str(x) for x in v)})"
        lines.append(f"    --motion-{k}: {v};")

    lines.append("}")

    # ── per-tier overrides ───────────────────────────────────────────────────
    for tier, query in TIERS:
        overrides = [
            f"        --fs-{role}: {node['$value'][tier]};"
            for role, node in t["scale"].items()
            if not role.startswith("$") and node["$value"][tier] != node["$value"][BASE_TIER]
        ]
        if not overrides:
            continue
        lines += ["", f"{query} {{", "    :root {"] + overrides + ["    }", "}"]

    OUT.write_text("\n".join(lines) + "\n")
    n_colors = len(colors)
    n_lines = len(lines)
    print(f"Wrote {OUT} — {n_colors} colours, {n_lines} lines, "
          f"{len(TIERS)} tier override blocks.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
