"""Generate DESIGN_RULES/tokens.md — the always-current token inventory.

Reads every :root block in static/css/general.css (the default block plus the
tier re-declarations inside media queries) and writes one markdown reference
table per token family. The output is AUTO-GENERATED: hand-edits are
overwritten. Regenerate with `make tokens` after any :root change.

This exists because hand-copied token tables drift (see DESIGN_RULES/README.md
findings [B-5], [N-5], [D-1]) — a generated inventory cannot.
"""
import re
import sys
from pathlib import Path

GENERAL = Path("static/css/general.css")
OUT = Path("DESIGN_RULES/tokens.md")

# Media-query context -> column label, in display order.
TIERS = [
    ("default", "Default"),
    ("max-width: 64rem", "Tablet ≤64rem"),
    ("max-width: 37.5rem", "Phone ≤37.5rem"),
    ("min-width: 90rem", "Wide ≥90rem"),
]

FAMILIES = [
    ("Typography", ("fs-", "lh-", "fw-", "font-")),
    ("Color", ("main-", "secondary-", "page-", "link-", "line-", "selection-",
               "accent-", "cat-", "status-", "r-", "house-", "field-",
               "icon-", "scrollbar-")),
    ("Spacing & layout", ("space-", "gutter-", "section-", "header-",
                          "menu-", "para-", "btn-", "block-", "content-")),
    ("Motion & surface", ("ani-", "hover-", "bg-")),
]


def _tier_of(media_query):
    if media_query is None:
        return "default"
    for needle, _ in TIERS[1:]:
        if needle in media_query:
            return needle
    return None  # print / unknown — skipped


def read_tokens(css):
    """{token: {tier: value}} from every :root block, tier-aware."""
    tokens = {}
    depth = 0
    media = None          # innermost @media selector text, if any
    media_depth = None
    root_depth = None
    for line in css.splitlines():
        opens, closes = line.count("{"), line.count("}")
        head = line.split("{")[0].strip()
        if opens and head.startswith("@media"):
            media, media_depth = head, depth
        if opens and head == ":root":
            root_depth = depth
        if root_depth is not None:
            m = re.match(r"\s*--([a-z0-9-]+):\s*([^;]+);\s*(?:/\*.*)?$", line)
            if m:
                tier = _tier_of(media)
                if tier is not None:
                    tokens.setdefault(m.group(1), {}).setdefault(
                        tier, m.group(2).strip())
        depth += opens - closes
        if root_depth is not None and depth <= root_depth:
            root_depth = None
        if media_depth is not None and depth <= media_depth:
            media, media_depth = None, None
    return tokens


def family_of(name):
    for label, prefixes in FAMILIES:
        if name.startswith(prefixes):
            return label
    return "Other"


def esc(value):
    return value.replace("|", "\\|")


def main():
    tokens = read_tokens(GENERAL.read_text(encoding="utf-8"))
    groups = {}
    for name in sorted(tokens):
        groups.setdefault(family_of(name), []).append(name)

    lines = [
        "<!-- AUTO-GENERATED by generate_token_reference.py — do not edit.",
        "     Regenerate with `make tokens` after any :root change. -->",
        "",
        "# Token Reference (generated)",
        "",
        f"Every `--*` token defined in `static/css/general.css :root` — "
        f"{len(tokens)} tokens. Blank tier cells inherit **Default**. "
        "For what a token *means*, see the hand-written rules: "
        "[typography.md](./typography.md), [color.md](./color.md), "
        "[layout.md](./layout.md), [responsive.md](./responsive.md).",
    ]
    order = [label for label, _ in FAMILIES] + ["Other"]
    for label in order:
        names = groups.get(label)
        if not names:
            continue
        lines += ["", f"## {label}", ""]
        lines.append("| Token | " + " | ".join(t for _, t in TIERS) + " |")
        lines.append("|---" * (len(TIERS) + 1) + "|")
        for name in names:
            cells = [esc(tokens[name].get(key, "")) for key, _ in TIERS]
            lines.append(f"| `--{name}` | " + " | ".join(
                f"`{c}`" if c else "" for c in cells) + " |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(tokens)} tokens).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
