import os
import re
from datetime import datetime

from lib.site import env, output_dir, pages, structures, articles


def news_slug_from_pagelink(page_link):
    """Extract the news slug from a pageLink like '/news/2026-foo/' -> '2026-foo'."""
    return page_link.rstrip('/').rsplit('/', 1)[-1] if page_link else ''


def prepare():
    """Module-level news preprocessing moved verbatim from build.py.
    Mutates the shared structures dict in place."""
    # Annotate news listing items with a small thumbnail when their detail page
    # has a hero image (0.* in contents/news/images/{slug}/). The listing shows
    # the 200w WebP variant emitted by compress_and_convert_images().
    _NEWS_IMG_EXTS = ('.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp')
    for _section in structures.get('news', []):
        for _item in _section.get('items', []):
            _plink = _item.get('pageLink', '')
            if not _plink.startswith('/news/'):
                continue
            _slug = news_slug_from_pagelink(_plink)
            _folder = os.path.join('contents', 'news', 'images', _slug)
            if os.path.isdir(_folder) and any(
                    os.path.exists(os.path.join(_folder, f'0{_e}')) for _e in _NEWS_IMG_EXTS):
                _item['thumb'] = f'/assets/news/{_slug}/0-200w.webp'

    # Year-grouped view for the news listing page: newest year first, items
    # newest-first within each year (source items are oldest-first).
    _news_years = []
    for _section in structures.get('news', []):
        for _item in _section.get('items', [])[::-1]:
            _yr = '20' + _item.get('year', "'00")[1:]
            if not _news_years or _news_years[-1]['year'] != _yr:
                _news_years.append({'year': _yr, 'items': []})
            _news_years[-1]['items'].append(_item)
    structures['news_years'] = _news_years


# Function to render individual news item pages from news.json
def render_news_pages():
    template = env.get_template('pages/news/news-item.html')
    image_extensions = {'.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp'}

    rendered_slugs = set()
    for section in structures.get('news', []):
        # Newest-first: when two listing items point at the same pageLink
        # (e.g. two news mentions of one story), the most recent item supplies
        # the page metadata and earlier duplicates are skipped.
        for item in section.get('items', [])[::-1]:
            page_link = item.get('pageLink')
            if not page_link:
                continue

            # Derive slug from pageLink (e.g. /news/2026-foo/ → 2026-foo)
            slug = news_slug_from_pagelink(page_link)
            if slug in rendered_slugs:
                continue
            rendered_slugs.add(slug)

            # Load markdown article content. Rewrite inline image references
            # (e.g. /assets/news/{slug}/3.jpg) to the 1200w WebP variant since
            # the raw originals are no longer copied to docs/.
            article_key = f'news/{slug}'
            news_content = articles.get(article_key)
            if news_content:
                # Match the same extensions compress_and_convert_images()
                # converts, so an inline .gif/.bmp/.tiff isn't left pointing at
                # an original that never gets copied to docs/.
                news_content = re.sub(
                    r'src="(/assets/news/[^"]+?)\.(?:jpe?g|png|gif|bmp|tiff)"',
                    r'src="\1-1200w.webp"',
                    news_content
                )

            # Discover images from contents/news/images/{slug}/. Output paths
            # point at WebP variants generated by compress_and_convert_images.
            img_folder = os.path.join('contents', 'news', 'images', slug)
            news_images = []
            if os.path.exists(img_folder):
                files = sorted(
                    [f for f in os.listdir(img_folder)
                     if not f.startswith('.') and
                     any(f.lower().endswith(ext) for ext in image_extensions)],
                    key=lambda x: (0, int(x.rsplit('.', 1)[0])) if x.rsplit('.', 1)[0].isdigit() else (1, x)
                )
                # Pass stems (no extension, no -Nw suffix); template builds srcset.
                news_images = [f'/assets/news/{slug}/{os.path.splitext(f)[0]}' for f in files]

            item = dict(item)
            if news_content:
                item['content'] = news_content

            # If a 0.{ext} source exists, use it as the hero. imgPath points at
            # the 1200w WebP variant — used by OG/Twitter meta and JSON-LD.
            # imgPathFront is the bare stem so the template can build srcset.
            if not item.get('imgPath') and os.path.exists(img_folder):
                for ext in image_extensions:
                    if os.path.exists(os.path.join(img_folder, f'0{ext}')):
                        item['imgPathFront'] = f'/assets/news/{slug}/0'
                        item['imgPath'] = f"{item['imgPathFront']}-1200w.webp"
                        news_images = [img for img in news_images
                                       if img.rsplit('/', 1)[-1] != '0']
                        break

            md_path = f"contents/news/articles/{slug}.md"
            try:
                date_modified = datetime.fromtimestamp(os.path.getmtime(md_path)).strftime("%Y-%m-%dT%H:%M:%S")
            except OSError:
                date_modified = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")

            output = template.render(
                news=item,
                news_images=news_images,
                pages=pages,
                structures=structures,
                year=datetime.now().year,
                date_modified=date_modified,
            )

            page_dir = os.path.join(output_dir, page_link.lstrip('/'))
            os.makedirs(page_dir, exist_ok=True)
            with open(os.path.join(page_dir, 'index.html'), 'w', encoding='utf-8') as f:
                f.write(output)
            print(f"News item page generated: {page_link}")

    print("News item pages rendered successfully!")
